import React from 'react'
export const metadata={
  title: "Service",
  description: "Generated by create next app",
};
const page = () => {
  return (
    <div className='text-5xl text-yellow-200 flex justify-center w-full h-screen items-center bg-yellow-900'>
      This is Service page
    </div>
  )
}

export default page
