import Link from "next/link";

export const metadata = {
  title: "Contact",
  description: "Generated by create next app",
};

const Page = () => {
  return (
    <div className="text-5xl text-yellow-200 flex flex-col justify-center w-full h-screen items-center bg-red-900 gap-10">
      
      <div className="flex justify-center gap-5">
        <Link
          href="/contact/manager"
          className="rounded-2xl bg-yellow-800 px-10 py-5 hover:bg-yellow-900"
        >
          Manager
        </Link>

        <Link
          href="/contact/employee"
          className="rounded-2xl bg-yellow-800 px-10 py-5 hover:bg-yellow-900"
        >
          Employee
        </Link>
      </div>

      This is Contact page
    </div>
  );
};

export default Page;