import React from "react"
export const metadata={
  title: "Charts",
  description: "Generated by create next app",
};
export default function chartLayout  ({children ,barChart , heatMap, sideBar}:{
  children : React.ReactNode,
  barChart : React.ReactNode, 
  heatMap : React.ReactNode
  sideBar : React.ReactNode
}){
 return(
  <div className="flex flex-col justify-center align-center ">{children}
  <div className="flex justify-evenly bg-red-900">
    
  <div className="bg-yellow-500 mx-10 ">
    {sideBar}
  </div>
  <div className="bg-red-500 w-full">
    {barChart}
  </div>
  <div className="bg-green-500 w-full">
    {heatMap}
  </div>
  </div>
  </div>
 )
}
