import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { AuthModalProvider } from "./context/AuthModalContext";
// import LoginModal from "./components/LoginModal";
import SignupModal from "./components/SignupModel";
import LoginModal from "./components/LoginModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin", "latin-ext", "cyrillic"],
});

const robotoMono = Geist_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin", "latin-ext", "cyrillic"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin", "latin-ext", "cyrillic"],
});

export const metadata = {
  title: {
    template: "%s | Amit App",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${robotoMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AuthModalProvider>
        <Navbar />
          <LoginModal/>
          <SignupModal/>
        {children}
        </AuthModalProvider>
      </body>
    </html>
  );
}
