import React, { Suspense } from 'react'
import Review from './components/Review';
import { Geist_Mono } from "next/font/google";
import ClientComp from './components/ClientComp';
import { getUsers } from '../lib/data';
import { User } from './types/user';
import UseRouter from './components/UseRouter';
 
const robotoMono = Geist_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin", "latin-ext", "cyrillic",],
});
export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

const Page = async () => {
  const users: User[] = await getUsers();
  return (
    <div className="relative min-h-screen w-full flex items-center justify-center text-white">

      {/* 🌄 Background Image */}
      <div
        className="absolute inset-0 bg-cover bg-center"
        style={{
          backgroundImage:
            "url('https://images.unsplash.com/photo-1506744038136-46273834b3fb')",
        }}
      />

      {/* 🌑 Dark Overlay */}
      <div className="absolute inset-0 bg-black/70 backdrop-blur-sm" />

      {/* 🌟 Main Content */}
      <div className="relative z-10 w-11/12 md:w-9/12 flex flex-col items-center gap-8">

        {/* 🏠 Heading */}
        <h1 className="text-4xl md:text-6xl font-bold text-yellow-300 drop-shadow-lg pt-10" style={{ fontFamily: "var(--font-roboto-mono)" }}>
          Home Page
        </h1>

        {/* 📦 Review Section
        <div className="w-full bg-white/10 backdrop-blur-md rounded-2xl p-6 shadow-lg border border-white/20">
          <Suspense
            fallback={
              <div className="text-center text-gray-300 animate-pulse">
                Loading reviews...
              </div>
            }
          >
            <Review />
          </Suspense>
        </div> */}

        {/* 👥 Client Component Section */}
        <div className="w-full text-black rounded-2xl p-6 shadow-xl flex flex-col justify-center border border-white/20">
          <ClientComp users={users} />
          <UseRouter/>
   
        </div>

      </div>
    </div>
  );
};

export default Page;